### ISSUE TITLE
opn_nat_port_forward doc?

### ISSUE THREAD

**Issue by rvalle** [naturalis/ansible-opnsense#67]
Where can I find a demo NAT port forward rule?

I thought I saw one somewhere...

**Comment by zerwes** [comment]
Hello @rvalle
Just a short excerpt/draft from my cfg:
```yml
opn_unset:
  - system/disablenatreflection
opn_nat_settings:
  - nat/outbound/mode: "advanced"

opn_nat_port_forward:
  - descr: DNAT ssh
    settings:
      - key: interface
        value: wan
      - key: ipprotocol
        value: inet
      - key: protocol
        value: tcp
      - key: tag
        value: null
      - key: tagged
        value: null
      - key: poolopts
        value: null
      - key: target
        value: 10.10.8.10
      - key: local-port
        value: 22
      - key: source/address
        value: OUR_PUBLIC_IPs  # restricted SRC, can be any too ...
      - key: destination/network
        value: wanip
      - key: destination/port
        value: 22000
      - key: natreflection
        value: purenat
      - key: associated-rule-id
        value: pass
  - descr: DNAT https
    settings:
      - key: interface
        value: wan
      - key: ipprotocol
        value: inet
      - key: protocol
        value: tcp
      - key: tag
        value: null
      - key: tagged
        value: null
      - key: poolopts
        value: null
      - key: target
        value: 10.10.8.10
      - key: local-port
        value: 443
      - key: source/address
        value: OUR_PUBLIC_IPs  # restricted SRC
      - key: destination/network
        value: wanip
      - key: destination/port
        value: 44300
      - key: natreflection
        value: purenat
      - key: associated-rule-id
        value: pass
```
hope it helps ...
works at least with [our fork](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense)
